---
version: '1.0'
output-on-error:
  error: Error condition
input:
  - items:
      - foo
      - bar
tasks:
  random_task:
    retry:
      delay: 4
      count: 15
    with:
      items: i in <% $.items %>
      concurrency: 4
    action: core.noop
